

services:

  clickhouse:
      ports:
        - '8124:8123'
        - '9001:9000'
      image: clickhouse/clickhouse-server:24.12
      restart: always
      environment:
        CLICKHOUSE_USER: demo
        CLICKHOUSE_PASSWORD: demo
        CLICKHOUSE_DB: demo
      ulimits:
        nproc: 65535
        nofile:
          soft: 262144
          hard: 262144
      volumes:
        - clickhouse-data:/var/lib/clickhouse

  pg:
    image: postgres:13
    restart: always
    ports:
      - "53321:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongo:
    image:  mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_DATABASE: demo
    ports:
      - "27028:27017"
    volumes:
      - mongo-data1:/data/db

  mysql:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - mysql-data:/var/lib/mysql

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - DB_VENDOR=postgres
        - DB_ADDR=pg
        - DB_DATABASE=demo
        - DB_USER=demo
        - DB_PASSWORD=demo
      ports:
        - "8080:8080"
      depends_on:
        - pg
      volumes:
        - keycloak-data:/opt/keycloak/data


volumes:
  clickhouse-data:
  pg-data:
  mongo-data1:
  mysql-data:
  keycloak-data:
