allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  adminforth: true
  better-sqlite3: true
  classic-level: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@adminforth/i18n'
  - adminforth
  - '@adminforth/agent'
