import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import typedocSidebar from "./docs/api/typedoc-sidebar.cjs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.'
    },
  ],

  mySidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: typedocSidebar,
    },
  ],


  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
