
FROM {{dockerBaseImage}}
WORKDIR /code/
ADD package.json {{dockerAdditionalManifestFiles}} /code/
RUN {{packageManager}} {{dockerPackageInstallSubcommand}}  
ADD . /code/
RUN {{packageManagerExec}} adminforth bundle
CMD ["sh", "-c", "{{packageManagerRun}} migrate:prod && {{packageManagerRun}} prod"]