name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'adminforth/documentation/**'
      - '.github/workflows/deploy_documentation.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: adminforth/documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: adminforth/documentation/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build

      - name: Deploy docs
        run: npm run deploy
