packages:
  - spa

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@adminforth/connector-sqlite@1.0.0'
  - adminforth@2.72.3
  - '@adminforth/connector-clickhouse@1.0.1'
  - '@adminforth/connector-mongo@1.0.0'
  - '@adminforth/connector-mysql@1.0.0'
  - '@adminforth/connector-postgres@1.0.0'

overrides:
  adminforth: 'link:'
